#!/bin/bash

SESSION_NAME="workspace"

tmux new-session -d -s $SESSION_NAME

tmux rename-window -t $SESSION_NAME:1 main

tmux new-window -t $SESSION_NAME -a -n side-arm
tmux split-window -h
tmux send-keys -t side-arm.left "cd ~/Code && clear" Enter
tmux send-keys -t side-arm.right "cd ~/Code && clear" Enter

tmux new-window -t $SESSION_NAME -a -n misc

tmux new-window -t $SESSION_NAME -a -n monitoring
tmux split-window -v
tmux select-pane -t monitoring.top
tmux resize-pane -D 60
tmux send-keys "htop" Enter

tmux select-window -t main

tmux attach-session -t $SESSION_NAME
